# Generated by Django 4.1.5 on 2023-01-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(to='posts.authors', verbose_name='Авторы'),
        ),
    ]
