# Generated by Django 4.1.5 on 2023-01-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_authors_remove_books_authors_books_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=88)),
                ('image', models.FileField(upload_to='image/')),
                ('authors', models.ManyToManyField(to='posts.authors', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BookPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88)),
                ('authors', models.ManyToManyField(to='posts.authors', verbose_name='Авторы')),
                ('book', models.ManyToManyField(to='posts.books', verbose_name='Книги')),
                ('category', models.ManyToManyField(to='posts.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
