# Generated by Django 4.1.5 on 2023-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_books_options_category_bookpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpages',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='bookpages',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookpages',
            name='category',
        ),
        migrations.AddField(
            model_name='bookpages',
            name='pages',
            field=models.FileField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(to='posts.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
