# Generated by Django 4.1.5 on 2023-01-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_bookpages_authors_remove_bookpages_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='bookpages',
            options={'verbose_name': 'Страниц', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
