# Generated by Django 4.1.5 on 2023-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_authors_options_alter_bookpages_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPages',
        ),
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.FileField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
