# Generated by Django 4.1.5 on 2023-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_bookpages_books_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.ManyToManyField(to='posts.books', verbose_name='Книги'),
        ),
    ]
